---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: rundeck-alpine-edge
    image: alpine:edge
    command: sh -c "while true ; do sleep 1 ; done"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        rundeck_ignore_docker: no
        service_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: alpine-edge
